language: generic
env:
  - PPA=yes
  - PPA=no

before_install:
  - uname -a
  - echo ja_JP.UTF-8 UTF-8 | sudo tee -a /var/lib/locales/supported.d/local
  - echo ja_JP.UTF-8 UTF-8 | sudo tee -a /etc/locale.gen
  - sudo /usr/sbin/locale-gen

install:
  - if [ x"$PPA" == "xyes" ] ; then sudo add-apt-repository ppa:pi-rho/dev -y; fi
  - sudo apt-get update -q
  - sudo apt-get install vim-nox

before_script:
  - export VIMLINT=/tmp/vim-vimlint
  - export VIMLPARSER=/tmp/vim-vimlparser
  - export VIMTHEMIS=/tmp/vim-themis
  - export VIMPROC=/tmp/vimproc.vim
  - export VITALVIM=/tmp/vital.vim
  - git clone https://github.com/syngan/vim-vimlint                --single-branch --depth 1 $VIMLINT
  - git clone https://github.com/ynkdir/vim-vimlparser             --single-branch --depth 1 $VIMLPARSER
  - git clone https://github.com/thinca/vim-themis --branch v1.4.1 --single-branch --depth 1 $VIMTHEMIS
  - git clone https://github.com/Shougo/vimproc.vim                --single-branch --depth 1 $VIMPROC
  - git clone https://github.com/vim-jp/vital.vim                  --single-branch --depth 1 $VITALVIM
  - (cd $VIMPROC && make)

script:
  - vim --cmd version --cmd quit
  - ./test/run_all.sh
