language: ruby
install:
  - git clone https://github.com/thinca/vim-themis
script:
  - vim --version
  - vim --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit
  - vim-themis/bin/themis --runtimepath vital.vim --reporter spec
