language: generic
env:
  - PPA=yes
  - PPA=no
before_install:
  - uname -a
  - echo ja_JP.UTF-8 UTF-8 | sudo tee -a /var/lib/locales/supported.d/local
  - echo ja_JP.UTF-8 UTF-8 | sudo tee -a /etc/locale.gen
  - sudo /usr/sbin/locale-gen
install:
  - if [ x"$PPA" == "xyes" ] ; then sudo add-apt-repository ppa:pi-rho/dev -y; fi
  - sudo apt-get update -q
  - sudo apt-get install vim-nox
before_script:
  - git clone https://github.com/thinca/vim-themis
  - git clone https://github.com/vim-jp/vital.vim
  - git clone https://github.com/Shougo/vimproc.vim
  - (cd vimproc.vim && make)
script:
  - vim --version
  - vim --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit
  - vim-themis/bin/themis --runtimepath vital.vim --runtimepath vimproc.vim --reporter dot
  - vim-themis/bin/themis --runtimepath vital.vim --reporter dot
